-- Table: public.Konaklama

-- DROP TABLE IF EXISTS public."Konaklama";

CREATE TABLE IF NOT EXISTS public."Konaklama"
(
    "BarinakID" integer NOT NULL,
    "KonakNo" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "KonakDurum" character varying(50) COLLATE pg_catalog."default" DEFAULT 'Boş'::character varying,
    CONSTRAINT "KonakNo" UNIQUE ("KonakNo"),
    CONSTRAINT "BarınakID" FOREIGN KEY ("BarinakID")
        REFERENCES public."Barinaklar" ("BarinakID") MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Konaklama"
    OWNER to postgres;

-- Trigger: kapasite_kontrol_tetikleyici

-- DROP TRIGGER IF EXISTS kapasite_kontrol_tetikleyici ON public."Konaklama";

CREATE OR REPLACE TRIGGER kapasite_kontrol_tetikleyici
    BEFORE INSERT
    ON public."Konaklama"
    FOR EACH ROW
    EXECUTE FUNCTION public.kapasite_kontrol_trigger();